### ISSUE TITLE
Make vitest a peer dependency or expose vitest bin

### ISSUE THREAD

**Issue by tobiasdiez** [danielroe/nuxt-vitest#180]
Currently, nuxt-vitest declares vitest as a dependency. However, it is not possible to invoke binaries exposed by transitive dependencies (at least for yarn, see https://github.com/yarnpkg/berry/issues/1875). Thus users are forced to install vitest as well, so that you end up with two versions of vitest which might lead to version mismatches and issues such as https://github.com/danielroe/nuxt-vitest/issues/132.

Proposal:
- Either make vitest a peer dependency
- Re-expose the vitest binary in nuxt-vitest

**Comment by danielroe** [comment]
I think it would make sense for `vitest` to be a peerDep.

**Comment by danielroe** [comment]
resolved in https://github.com/danielroe/nuxt-vitest/commit/616b72133d99ddb06fd7cd0699554d9834edfa3f.

**Comment by marr** [comment]
Thanks for this @danielroe - I just realized that the dep is a bit restrictive due to vitest still being prerelease (<1). Should the version be something like `~0` to support all pre-release versions of vitest?  Currently if you `$ ni -D @nuxt/test-utils nuxt-vitest` on a fresh nuxt install, this will fail.
