### ISSUE TITLE
Mocking multiple iterations of nuxt imports in the same test file

### ISSUE THREAD

**Issue by joesobo** [danielroe/nuxt-vitest#65]
Hey I was using `mockNuxtImport` to mock 2 different users from a nuxt composable in the same test file. It seems to use the last `mockNuxtImport` that is called in the file, not the one scoped to the test.

```ts
it('renders the users email', () => {
	mockNuxtImport('useSupabaseUser', () => {
		return () => mockUser
	})

	render(User)

	expect(screen.getByText('jdoe@gmail.com')).toBeInTheDocument()
})

it('renders the Error when there is no user', () => {
	mockNuxtImport('useSupabaseUser', () => {
		return () => {}
	})

	render(User)

	expect(screen.getByText('Error')).toBeInTheDocument()
})
```

The first test fails here as it thinks `useSupabaseUser` returns {}

I did manage to get this working with a global variable:

```ts
let mockUser = { id: 1, name: 'John Doe', email: 'jdoe@gmail.com' }

mockNuxtImport('useSupabaseUser', () => {
	return () => mockUser
})

it('renders the users email', () => {
	render(User)

	expect(screen.getByText('jdoe@gmail.com')).toBeInTheDocument()
})

it('renders the Error when there is no user', () => {
	mockUser = {}

	render(User)

	expect(screen.getByText('Error')).toBeInTheDocument()
})
```

Not really sure if this is expected, it seems a little strange to me, so figured I post my findings.

**Comment by dprbook** [comment]
Hi, so when we look at [here](https://github.com/danielroe/nuxt-vitest/blob/f9af5b61d19b3d45e131a5ab4b2f999c7b5461cf/packages/vitest-environment-nuxt/src/modules/mock.ts#L28), we see that `mockNuxtImport() is a macro, that is transformed to vi.mock().
Vi.mock is - as described [here](https://vitest.dev/api/vi.html#vi-mock) - hoisted up to the root of the file. So mocking the same function in the same file overwrites the mock.
I usually also do the same thing as you did: create a global variable, and redirect the mocked call to it. Then for each call overwrite the variable so the mocked call returns the new value.
On a side note, since we are in a testing context, declaring a global variable shouldn't be problematic. In a regular application context, I would not do it so lightly.
Hope that helps :)

**Comment by danielroe** [comment]
Would be nice to add a note to explain this a bit more.

**Comment by nicolaspayot** [comment]
I had the same issue and did the same thing. I'd be happy to add a note about this in a PR if you want @danielroe

**Comment by danielroe** [comment]
Thank you @nicolaspayot ❤️
